### PR TITLE
Add deck_uuid param to saveDeckAction and publishDeckAction

### LINKED ISSUE #599: Option to save deck by uuid

### PR DESCRIPTION
**Pull request by North101**
Fixes #599

Note: I haven't tested this because I am not sure how to run it locally.

### CODE REVIEW

**Review by NoahTheDuke — APPROVED** [review]

**Comment by NoahTheDuke** [comment]
Should we be worried about it choosing uuid if both are provided?

**Comment by North101** [comment]
> Should we be worried about it choosing uuid if both are provided?

So the reason I wrote it that way is because I was under the assumption that you were moving from id to uuid. Im happy to flip the logic if you would prefer the other way around.

**Comment by NoahTheDuke** [comment]
Ah yeah, that's a good point. Cool, then I think this is good.

**Comment by plural** [comment]
let me patch this in and take it for a spin tonight.

**Comment by plural** [comment]
I'm still doing some testing (and getting distracted by trying to work up some instructions for local oauth testing...), but there is a syntax issue to fix.

**Comment by North101** [comment]
> I'm still doing some testing (and getting distracted by trying to work up some instructions for local oauth testing...), but there is a syntax issue to fix.

Woops fixed.

**Comment by North101** [comment]
> Should we be worried about it choosing uuid if both are provided?

So one option is to error if both are provided

**Comment by plural** [comment]
Hiya!  Sorry for the radio silence on this.  I did end up patching both of your PRs in and making a couple changes.  I need to grab the machine i did that on and get you and update. 

Largely this is good, but it exposed a couple rough edges for us.

Thanks for the patience *and* for the contributions!

**Comment by locks** [comment]
@plural anything I can help with?

**Comment by plural** [comment]
I apologize for letting this linger as long as it has.  With the progress on the new versions of NRDB (v2) and the API (v3), i'm going to close this one out.  That new API is UUID only to start.

**Pull request closed without merging**
