### PR TITLE
replace each MWL reference with Legality

### PR DESCRIPTION
**Pull request by francescopellegrini**
There were a few places where the "MWL" term was still used.

### CODE REVIEW

**Comment by francescopellegrini** [comment]
Also #308 could be worth a fix.

**Comment by francescopellegrini** [comment]
I just noticed that both [deck search syntax](https://netrunnerdb.com/en/syntax) and [advanced search](https://netrunnerdb.com/en/search) refer to the terms "Banlist" / "Ban List" instead.. which one should we prefer?

**Comment by plural** [comment]
we should probably use Ban List or ban list as two words consistently.

**Comment by francescopellegrini** [comment]
> we should probably use Ban List or ban list as two words consistently.

@plural so would it help if I open a new PR to update all terms to "Ban List"? ;)

**Comment by plural** [comment]
sure thing that would be swell!

-jason

**Pull request merged**
