### PR TITLE
Search Improvements

### LINKED ISSUE #552: Draft cards show up in a standard search
https://netrunnerdb.com/find/?q=b%3Astandard-ban-list-21-06+z%3Arotation-2021+c%3A0&sort=name&view=list&_locale=en

The above link should show a blank search. Draft IDs are counted as "in rotation". They should be excluded from all standard format rotations.

### LINKED ISSUE #553: Feature Request: mini faction quick filter
Is there a way we could get "AD"/"AP"/"SL" added as filters for the three mini factions?

### PR DESCRIPTION
**Pull request by distributive**
- Resolves #552 - draft cards can no longer appear when a rotation is specified (this isn't a perfect solution but is unlikely to ever be a problem - the ideal fix would be to have draft and standard be explicit formats)
- Fixed `f:-` only finding neutral corp cards (now finds neutral runner cards as well)
- Added the following shortcuts: 
  - `nc` - Neutral corp cards
  - `nr` - Neutral runner cards
  - `neutral` - Alternative shortcut for all neutral cards
  - `ap`, `ad`, `su` - Alternative shortcuts for the mini-factions (resolves #553)
  - `mini` - All mini-factions
  - `hb` - HB
  - `weyland` - Weyland
- Updated and fixed the search syntax reference
- The search syntax reference is now linked when a search fails to find any cards

### CODE REVIEW

**Review by NoahTheDuke — APPROVED** [review]
Looks good to me. Can't believe I got the hash array backwards and overwrote neutral runner.

**Comment by NoahTheDuke** [comment]
Oh, make sure to update the tooltip syntax reference too. It's slightly different which is annoying.

**Comment by distributive** [comment]
> Oh, make sure to update the tooltip syntax reference too. It's slightly different which is annoying.

What's the best way to fit it concisely in? Does this work:
`f - faction (faction code, letter, or '-' for neutral)`

**Comment by NoahTheDuke** [comment]
Yeah that seems short and sweet to me. I remember making concessions like that for the others (on my phone or I'd look it up lol).

**Review by plural — APPROVED** [review]
This is great!

**Pull request merged**
