### PR TITLE
Fix the sort function for the deck building page.

### LINKED ISSUE #306: Sort on Build tab of Deckbuilder page doesn't work
Clicking the column headers doesn't seem to do anything any more:

image

Tested on all columns, both Chrome and Firefox, two different users.

### PR DESCRIPTION
**Pull request by plural**
select_only_latest_cards should not do filtering *and* sorting.

Fixes #306

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
Looks good, nice one!

**Comment by NoahTheDuke** [comment]
Where is `normalized_title` coming from? It’s not defined for cards in the card data.

And without the `_.deburr` line, you lose the fix for searching for cards like Déja Vu and Sifr by name in the deck search.

**Comment by x3N1GM4x** [comment]
It's almost like I didn't do any regression testing before I merged, just checked it fixed the bug. 😛

**Comment by NoahTheDuke** [comment]
It’s all good, NRDB is arcane and byzantine.

**Comment by plural** [comment]
@NoahTheDuke : i'm seeing normalized_title populated in the results of NRDB.data.cards.find() calls and the type-ahead in the search box on the building page is still working.  I'm definitely not all that familiar with the normalized_title (except why it exists).  Are there other troubles here because of this patch or is all well?

**Comment by NoahTheDuke** [comment]
We already discussed this on slack, but to keep history public, `normalized_title` was removed in PR #310, as I had trouble invalidating users' cache, making it impossible to introduce a new field to the cards data.

**Comment by x3N1GM4x** [comment]
> NRDB is arcane and byzantine.

And now I learned a new word too. 😝

**Pull request merged**
