### PR TITLE
Display rotated icon

### PR DESCRIPTION
**Pull request by kamekura**
Displays 🔄 besides rotated cards in decklist page, and banned and restricted icons on card page.　This partially solves issue #214.

I accept suggestions for the "banned" icon.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Wanna post some pics of what this looks like?

**Comment by kamekura** [comment]
Tough to paste the images here on mobile so doing it on slack.

**Comment by kamekura** [comment]
I feel that there’s no consensus of what the spec should be, so I’m abandoning this PR...

**Comment by kamekura** [comment]
If anyone want to take over feel free.

**Comment by x3N1GM4x** [comment]
I definitely want us to do something around this, and can help to arrive at a consensus or just make an executive decision so that we do *something*. :)

Thanks for your work on this @kamekura, it's greatly appreciated.

**Comment by NoahTheDuke** [comment]
Hey @kamekura, no pressure to get a PR out fast! We're all busy and just haven't had time to put into reviewing/handling this.

**Pull request closed without merging**
