### PR TITLE
Remove extra .png at the end of the faction images in the suggestion box

### LINKED ISSUE #324: Suggestions show broken image for faction
The images for factions on the suggestion list show up like: https://netrunnerdb.com/images/factions/16px/haas-bioroid.png.png

I have a fix i'll send out for this.

### PR DESCRIPTION
**Pull request by plural**
Fixes #324

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
Tried to test this on my local, but couldn't get suggestions to actually work. I created about a dozen decks, published them all, ran the `app:suggestions` command on my box and made sure my settings were set up to show 3 or 10 suggestions, but still no joy. 

Can anyone confirm what the criteria are for having suggestions shown at all?

**Comment by plural** [comment]
i put a runner.json file that i copied down from nrdb in web/ and i was
able to get them to load.

I totaly missed the app:suggestions command to generate the files, though!
I should add that to the docker build steps.

**Comment by x3N1GM4x** [comment]
Haha, fair enough, I'll do the same for now. 😛

**Comment by x3N1GM4x** [comment]
FWIW, I think the issue is probably that I don't have enough decks in my local environment to put together suggestions, as no corp.json or runner.json file was created in `web` when I ran the command. 🤷‍♂️

**Comment by x3N1GM4x** [comment]
Turns out I was being dumb and didn't provide the right parameter(s) to the command, but I have the production json files now anyway, so will give this a quick test and then merge it! 😝

**Comment by x3N1GM4x** [comment]
Tested successfully on my local:
image
Nice one!

**Pull request merged**
