### PR TITLE
Add Hashing Value to URL Routing

### PR DESCRIPTION
**Pull request by jdeng89**
I honestly don't have any idea what I'm doing but here's my idea =|.

### CODE REVIEW

**Comment by alsciende** [comment]
Thank you @jdeng89 

My thoughts: it's still possible and quite easy to find the hash, since there is no salt. An attacker knows the targeted id and only has to compute some hashes with a few dates around the probable creation date. Also, the hash computation needs to be put in a separate service, and the hash can be computed server-side and sent to the front-side, no need to compute it front-side.

**Comment by alsciende** [comment]
So, the PR is interesting and a nice way to implement it. Create a service, inject %secret%, return hash based on deck.id, deck.creationDate and %secret%, and it should be good.

**Comment by gereons** [comment]
Since I like to be prepared: have you already decided if the proposed URL scheme going to stay?

**Comment by jdeng89** [comment]
Alright, I've removed the date (because I actually think there's a huge bug in it that I'm not sure how to fix) and I've added a salt instead which will randomize it per deck. (this is better than secret as it's random per deck)

**Comment by jdeng89** [comment]
I didn't actually do this because I'm not sure what the routing behavior is when there isn't a third path (hash), but in order to keep old decklist URLs safe, I should be able to just check whether or not either a salt exists or is empty string, and allow sharing to occur if it's empty (since all new Decks should have the salt set).

**Comment by NoahTheDuke** [comment]
Closing for now as the work needed to fix would be best suited for a new PR.

**Pull request closed without merging**
