### PR TITLE
Add Patreon button to nav bar

### PR DESCRIPTION
**Pull request by x3N1GM4x**
My first attempt at this - I am definitely no CSS/bootstrap expert, so I fully expect there to be a better way to do this, which I'd love someone to point out to me.

It took me a while to figure out where some of the CSS for the nav bar was coming from (twitter bootstrap) and how I could override it in our own css.

If someone could take a look and then show me how to achieve the same thing in a better way, that would be great!

### CODE REVIEW

**Comment by x3N1GM4x** [comment]
[P2: Add Patreon badge to site](https://trello.com/c/Xecha9Nw/66-p2-add-patreon-badge-to-site)

**Comment by NoahTheDuke** [comment]
The css looks fine, but I worry that placing it at the top (valuable real estate in an already cramped header) will feel grabby or overboard. I think I'd prefer to have it listed in the footer along with another image-link to donate with Paypal. There we can make them as big and flashy as we want, while not detracting overall from the usability of the site.

**Comment by x3N1GM4x** [comment]
Sure, I had the same thoughts, but thought that placement consistency between nisei.net and NRDB might be worth it. Let's discuss with the team before making a decision.

**Comment by plural** [comment]
i added a patreon button to the bottom section in a recent PR (#457) so i'm closing this out.

**Pull request closed without merging**
